### ISSUE TITLE
node version depends on module atob

### ISSUE THREAD

**Issue by s3ththompson** [briantbutton/md5-wasm#2]
I had to manually install [`atob`](https://www.npmjs.com/package/atob). Ideally that would be a dependency in `package.json` right?

**Comment by briantbutton** [comment]
s3ththompson, you are correct.  I have never gotten a build of NodeJS that does not include atob but I have now learned that such a thing must exist.  I will check that out and figure out something.

Node's treatment of atob has always been a puzzle to me but that is a different subject, I am sure.

**Comment by briantbutton** [comment]
s3ththompson, thanks again for the ticket.  'atob' in NodeJS is one line, as you see below, so I put it in a embedded function.  Not sure why Node does not do the same . . .

`Buffer.from(str,"base64").toString("binary")`
