### ISSUE TITLE
synchronous support

### ISSUE THREAD

**Issue by mfulton26** [briantbutton/md5-wasm#3]
Sometimes it is impractical to use asynchronous APIs and the use of synchronous ones is preferred. Sometimes I _want_ to block. Is this possible with WASM or does all WASM-JS interop require the use of async APIs? I would love to be able to use `md5-wasm` synchronously in a window and/or worker scope. Thank you.

**Comment by briantbutton** [comment]
Sorry for the delay.  'md5JS', starting roughly on line 300, calculates and returns directly.  You could hotwire the existing code to call it and return the result directly, instead of a promise.  Basically, you would collapse the lines between 45 and 115 to a simple function call.

Happy coding!
